USE LearningSQL;

CREATE TABLE Rooms (
	Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	RoomNumber VARCHAR(255) NOT NULL,
	Size VARCHAR(255) NOT NULL,
	Occupied INT,
	UserId INT NOT NULL,
	FOREIGN KEY(UserID) REFERENCES Users(Id)
);